# Generated by Django 6.0 on 2025-12-22 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecifiedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('mh', models.BooleanField(default=False)),
                ('sd', models.BooleanField(default=False)),
                ('dd', models.BooleanField(default=False)),
                ('ref', models.BooleanField(default=False)),
                ('dsr', models.BooleanField(default=False)),
                ('zen', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specified_items', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='HaveListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='have_items', to=settings.AUTH_USER_MODEL)),
                ('specified_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_by', to='inventory.specifieditem')),
            ],
        ),
        migrations.CreateModel(
            name='WantListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done')], default='OPEN', max_length=10)),
                ('specified_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wanted_by', to='inventory.specifieditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='specifieditem',
            index=models.Index(fields=['item'], name='inventory_s_item_id_bc548b_idx'),
        ),
        migrations.AddIndex(
            model_name='specifieditem',
            index=models.Index(fields=['item', 'mh', 'sd', 'dd', 'ref', 'dsr', 'zen'], name='inventory_s_item_id_dd827c_idx'),
        ),
        migrations.AddConstraint(
            model_name='specifieditem',
            constraint=models.UniqueConstraint(fields=('item', 'mh', 'sd', 'dd', 'ref', 'dsr', 'zen'), name='uniq_specified_item_by_flags'),
        ),
        migrations.AddIndex(
            model_name='havelistitem',
            index=models.Index(fields=['user'], name='inventory_h_user_id_e48199_idx'),
        ),
        migrations.AddIndex(
            model_name='havelistitem',
            index=models.Index(fields=['specified_item'], name='inventory_h_specifi_a7e7f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='havelistitem',
            constraint=models.UniqueConstraint(fields=('user', 'specified_item'), name='uniq_user_have_specified_item'),
        ),
        migrations.AddIndex(
            model_name='wantlistitem',
            index=models.Index(fields=['user', 'status'], name='inventory_w_user_id_00cabd_idx'),
        ),
        migrations.AddIndex(
            model_name='wantlistitem',
            index=models.Index(fields=['specified_item'], name='inventory_w_specifi_e6722e_idx'),
        ),
        migrations.AddConstraint(
            model_name='wantlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'specified_item', 'status'), name='uniq_user_want_specified_item_status'),
        ),
    ]
